branch-defaults:
 default:
   environment: Durian-django-env
   group_suffix: null
environment-defaults:
 Durian-django-env:
   branch: null
   repository: null
 DurianGUI-env:
   branch: null
   repository: null
global:
 application_name: django-env
 branch: null
 default_ec2_keyname: Durian
 default_platform: Python 3.6
 default_region: us-east-1
 include_git_submodules: true
 instance_profile: null
 platform_name: null
 platform_version: null
 profile: eb-cli
 repository: null
 sc: null
 workspace_type: Application
